services:
  ftp:
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    ports:
      - 20-21:20-21
      - 10100-10110:10100-10110
    env_file:
      - .env
    networks:
      - net
    volumes:
      - wp:/var/www
  adminer:
    restart: always
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - net
    volumes:
      - adm:/usr/share/adminer
  mariadb:
    restart: always
    container_name: db
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - net
    env_file:
      - .env
  wordpress:
    restart: always
    container_name: wp
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - wp:/var/www
    networks:
      - net
    env_file:
      - .env
  nginx:
    restart: always
    container_name: proxy
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 1234:443
    volumes:
      - wp:/var/www
      - adm:/usr/share/adminer
    networks:
      - net
networks:
  net:
    driver: bridge

volumes:
  db:
    driver: local
  adm:
    driver: local
  wp:
    driver: local
