services:
  mariadb:
    container_name: db
    build:
      args:
        progress: plain
      context: requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - net
    env_file:
      - .env
  wordpress:
    container_name: wp
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - wp:/var/www
    networks:
      - net
    env_file:
      - .env
  nginx:
    container_name: proxy
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 1234:443
    volumes:
      - wp:/var/www
    networks:
      - net
networks:
  net:
    driver: bridge
volumes:
  db:
    driver: local
  wp:
    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /home/shai/inception/srcs/data/wp 
